type = "service_account"
project_id = "directed-seeker-456203-c1"
private_key_id = "7e04923a3b1b508973825f225b42e0bb4ac6eba6"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDnPD9wfURW3xMB
GKSPOl3xWk3UyLlQtafWmjP+RAIWma+SE8drUtvmg4sR3cECiDLJITKmboMMHTcw
yvCBnXkOs5Ee6gM1etGYkaOSmm7ogXgID5Tm76TAVtKuosPZ25wI4ogSqtgLQCIA
xEThzZgs0VdOp6OZYRpgoMYLA0JgzKRH0DQnA3yI+hQahKf7KG7MkmpNNAOCJtOi
E1NUzfy0nXoudwU0aaqi8v07iZowvCeSaspK5/m8KFBbxt8KcgUi/dDgJG1JAmj/
6OSwMD8v+VGH4sU9B4nUeS2FKtFiF+VsPSJr4GAMWM+GKHEF5hOzCAY465k49/wt
Z3wKHwAjAgMBAAECggEAC4iSQ3qZX4SLOUlGNUynJeQoBf59sRxhGDpNxey/dpVz
eo5DqpiR66VRA52eGbxlsr7V/L4otCsljGilkVl45yD8Eot/3c7X8yEEhHSb0Tta
m3r80CimJ4p3wgp6nqcDropvWLsDwUqRckdX24llLIsZLIz+WHv4PwHrOYkP6lhX
wUiF0m0tGf8oKoI9bO5tT4SHhMOJh5u+I1iGDWSCuRNdS4EHGLBhrd57D5XLeeRW
6QwNG+vSc3i5qj3JQJ4vzj9+aM98wtxlNea/3BpM8xkEGEsgk0/8g+rl0YprVb84
buD+fpr2+3oV5RhsdIFmaOrQICh5cGw7BRFNVInimQKBgQD5hMIldQPT2Jkp8V3P
O9IzRCBslHLccYjKJBJz2gtLrBRqX44PtV4qGZnHE8iw1/DsPHcWrvam0AENroYm
L6KIUguE6StjRxztcFW/PJ1Aki5b/GdVN6KEHIQt2AyCJGcOw0As296CRApmoQuy
LDu93FirTO/Xnpf1iPLgAuPrSQKBgQDtPej3gT9acDfP/YzsQrj0zjKa4LQ70fTr
+TGlNNU+RLbE2DehyUbPa266SAE0IvC79vIBbkOasEfNiFgPgVOtSRW/jCifhf07
lHxWCBmP/aP4F4uApEdXW1sagQwfviMCHgybKmwe0/T4dYOVLdBFz7KMuDjfsn76
Y4huaLDECwKBgQCJ5XfScZ/i5TKIfo8kp1/c20q8FzJ/Z/N8G4FjK17QvFIwE40U
W1ymEa3t2p4wNbc9J5F9JMbFm/DpGcmjsvG1OvqIwsAqxrNS+aE55grWE7OxPIXz
D6MuNgBKwbrv9aRLAVcnM3/+KBJDc79eAZomrG8IhKWMWWaL2Nq5OH+zmQKBgBIg
C791GXEAZ9M1LOIUCutxIX6hskNrvAmXRUq46Z3TRB9v4Xgz13wbWh9TRvxDux6x
NDYVxYZ491Nlmky89bakgcvbmnLtmrZFluY/wiw1FaTrr5XJd0XeTeyNdW6raSNN
RmtIZ3BHg0zENaRdFq9uudZ0cKvuiDL7Db5Zsz+XAoGBAOa4OhL/PmGXFETSGRnn
hYtSoTVz1M0zQBfmIHOPIQVd4lFdJ2gjXRuymSUU2N4m9+Z/6j1v82vuE/sIWEQ9
q9Qr2GBSP1N9z2JHBOJBsEU57rYGZx+NzdbviR/LiNakTwaptU6XiSFxbGg8GdKi
c3tv+iq+IQnL9/KOWgSt11Tx
-----END PRIVATE KEY-----"""

client_email = "ocr-892@directed-seeker-456203-c1.iam.gserviceaccount.com"
client_id = "112673856799793529346"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ocr-892%40directed-seeker-456203-c1.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
